# ===============[ ALL ]===============
ctf_user: "heroctf"
ctf_home: "/home/{{ ctf_user }}"

# ===============[ CTFD ]===============
ctfd_install_path: "{{ ctf_home }}/CTFd"
ctfd_version: "3.8.0"
ctfd_domain: "ctf.heroctf.fr"

ctfd_install_theme: true
ctfd_theme_name: "hacker_theme.zip"

ctfd_install_discord_webhook: true

ctfd_install_dkim: true
ctfd_dkim_private_key: "dkim_ctfd.key"

# ============[ CHALLENGES ]============
challenges_git_url: "git@github.com:HeroCTF/HeroCTF_v7.git"
challenges_install_path: "{{ ctf_home }}/challenges"

# ============[ DEPLOY DYNAMIC ]============
deploy_dynamic_install_path: "{{ ctf_home }}/deploy-dynamic"
